/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToanNM_PC09504_FinalTest;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ToanNM_PC09504
 */
public class FinalTest extends javax.swing.JFrame {

    //DefaultComboBoxModel model = new DefaultComboBoxModel();
    DefaultTableModel model = new DefaultTableModel();
    Connection ketNoi;
    String duongDan;

    /**
     * Creates new form FinalTest
     */
    public FinalTest() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Quản Lý Điện Thoại");
        DatTenCotPhongHoc();
        DoDuLieuLenBang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTenDienThoai = new javax.swing.JTextField();
        cboHangSanXuat = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblHinhAnh = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("QUẢN LÝ ĐIỆN THOẠI");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

        jLabel2.setText("Tên Điện Thoại");
        jPanel1.add(jLabel2);

        jLabel4.setText("Hãng Sản Xuất");
        jPanel1.add(jLabel4);

        jLabel5.setText("Số Lượng");
        jPanel1.add(jLabel5);

        jLabel3.setText("Đơn Giá");
        jPanel1.add(jLabel3);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 30));
        jPanel2.add(txtTenDienThoai);

        cboHangSanXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SamSung", "Iphone", "Oppo" }));
        jPanel2.add(cboHangSanXuat);
        jPanel2.add(txtSoLuong);
        jPanel2.add(txtDonGia);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel4.add(btnLoad);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel4.add(btnThem);

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel4.add(btnCapNhat);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel4.add(btnXoa);

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel4.add(btnTimKiem);

        btnSapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Statistics.png"))); // NOI18N
        btnSapXep.setText("Sắp Xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });
        jPanel4.add(btnSapXep);

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ngày Học", "Phòng Học", "Ca Học", "Địa Điểm", "Hình Ảnh"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        jLabel6.setText("Thành Tiền");

        txtThanhTien.setEditable(false);

        btnTinhTien.setText("Tính Tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTinhTien))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean check() {
        String mauPhong = "[1-5]{1}[0-9]{2}";
        String mauDonGia = "[-0-9,]{1,50}";
        String mauSoLuong = "[-0-9]{1,11}";
        if (txtTenDienThoai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên Điện Thoại");
            txtTenDienThoai.requestFocus();
            return false;
        }
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Lượng");
            txtSoLuong.requestFocus();
            return false;
        }
        if (!txtSoLuong.getText().matches(mauSoLuong)) {
            JOptionPane.showMessageDialog(this, "Số Lượng phải là số");
            txtSoLuong.requestFocus();
            return false;
        }
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        if (soLuong < 1) {
            JOptionPane.showMessageDialog(this, "Số Lượng phải lớn hơn 0");
            txtSoLuong.requestFocus();
            return false;
        }
        if (txtDonGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Đơn Giá");
            txtDonGia.requestFocus();
            return false;
        }
        if (!txtDonGia.getText().matches(mauDonGia)) {
            JOptionPane.showMessageDialog(this, "Đơn Giá không đúng định dạng");
            txtDonGia.requestFocus();
            return false;
        }
        int donGia = Integer.parseInt(txtDonGia.getText().replace(",", ""));
        if (donGia < 1000) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải lớn hơn 1,000");
            txtDonGia.requestFocus();
            return false;
        }
        if (lblHinhAnh.getIcon() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng thêm hình ảnh");
            return false;
        }
        return true;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (check()) {
                if (tblBang.getRowCount() > 0) {
                    for (int i = 0; i < tblBang.getRowCount(); i++) {
                        if (txtTenDienThoai.getText().equalsIgnoreCase(tblBang.getValueAt(i, 0).toString())) {
                            JOptionPane.showMessageDialog(this, "Trùng Tên Điện Thoại");
                            return;
                        }
                    }

                    KetNoiCSDL();
                    DecimalFormat df = new DecimalFormat("###,###");
                    String sql = "INSERT INTO DIENTHOAI VALUES(?,?,?,?,?)";
                    PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                    cauLenh.setString(1, txtTenDienThoai.getText());
                    cauLenh.setString(2, cboHangSanXuat.getSelectedItem().toString());
                    cauLenh.setInt(3, Integer.parseInt(txtSoLuong.getText()));
                    cauLenh.setInt(4, Integer.parseInt(txtDonGia.getText().replace(",", "")));

                    cauLenh.setString(5, duongDan);
                    cauLenh.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                    ketNoi.close();
                    DoDuLieuLenBang();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        txtTenDienThoai.setText("");
        txtTenDienThoai.setEditable(true);
        txtDonGia.setText("");
        cboHangSanXuat.setSelectedIndex(0);
        txtSoLuong.setText("");
        txtThanhTien.setText("");
        lblHinhAnh.setIcon(null);
        try {
            DoDuLieuLenBang();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            if (check()) {
                if (tblBang.getSelectedRow() == -1) {
                    JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng để Cập Nhật");
                } else {

                    KetNoiCSDL();
                    DecimalFormat df = new DecimalFormat("###,###");
                    String sql = "UPDATE DIENTHOAI SET HANGSANXUAT =?,SOLUONG=?,DONGIA=?,HinhAnh=? WHERE TENDIENTHOAI = ?";
                    PreparedStatement cauLenh = ketNoi.prepareStatement(sql);

                    cauLenh.setString(1, cboHangSanXuat.getSelectedItem().toString());
                    cauLenh.setInt(2, Integer.parseInt(txtSoLuong.getText()));
                    cauLenh.setInt(3, Integer.parseInt(txtDonGia.getText().replace(",", "")));
                    cauLenh.setString(4, duongDan);
                    cauLenh.setString(5, txtTenDienThoai.getText());

                    cauLenh.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
                    ketNoi.close();
                    DoDuLieuLenBang();
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        txtTenDienThoai.setEditable(false);
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        try {
            DanhSachGiay();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            if (tblBang.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng để xoá");
            } else {
                KetNoiCSDL();
                String sql = "DELETE DIENTHOAI WHERE TENDIENTHOAI =?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, txtTenDienThoai.getText());
                // Ban chac chan muon xoa khong
                int kq = JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Xoá");
                if (kq == JOptionPane.YES_OPTION) {
                    cauLenh.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công");
                    ketNoi.close();
                    DoDuLieuLenBang();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            String kq = JOptionPane.showInputDialog(this, "Nhập tên Điện Thoại muốn tìm", "Tìm Kiếm", JOptionPane.QUESTION_MESSAGE);
            if (kq.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Điện Thoại");
                kq = JOptionPane.showInputDialog(this, "Nhập tên Điện Thoại muốn tìm", "Tìm Kiếm", JOptionPane.QUESTION_MESSAGE);
            } else {
                try {
                    model.setRowCount(0);
                    KetNoiCSDL();
                    DecimalFormat df = new DecimalFormat("###,###");
                    String sql = "SELECT * FROM DIENTHOAI WHERE TENDIENTHOAI LIKE ?";
                    PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                    cauLenh.setString(1, "%" + kq + "%");
                    ResultSet ketQua = cauLenh.executeQuery();
                    while (ketQua.next() == true) {
                        String tenDienThoai = ketQua.getString(1);
                        String hangSanXuat = ketQua.getString(2);
                        int soLuong = ketQua.getInt(3);
                        int donGia = ketQua.getInt(4);
                        int tongTien = soLuong * donGia;
                        String donGiaFormatted = df.format(donGia);
                        String tongTienFormatted = df.format(tongTien);
                        String HinhAnh = ketQua.getString(5);

                        model.addRow(new Object[]{tenDienThoai, hangSanXuat, soLuong, donGiaFormatted, tongTienFormatted, HinhAnh});
                    }
                    ketNoi.close();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        try {
            model.setRowCount(0);
            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");

            String sql = "SELECT * FROM DienThoai ORDER BY DONGIA ASC";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            ResultSet ketQua = cauLenh.executeQuery();
            while (ketQua.next() == true) {
                String tenDienThoai = ketQua.getString(1);
                String hangSanXuat = ketQua.getString(2);
                int soLuong = ketQua.getInt(3);
                int donGia = ketQua.getInt(4);
                int tongTien = soLuong * donGia;
                String donGiaFormatted = df.format(donGia);
                String tongTienFormatted = df.format(tongTien);
                String HinhAnh = ketQua.getString(5);

                model.addRow(new Object[]{tenDienThoai, hangSanXuat, soLuong, donGiaFormatted, tongTienFormatted, HinhAnh});
            }
            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        JFileChooser chonFile = new JFileChooser("src\\HinhAnh\\");
        chonFile.showOpenDialog(null);
        File f = chonFile.getSelectedFile();
        if (f != null) {
            duongDan = "src\\HinhAnh\\" + f.getName();
            ImageIcon hinhAnh = new ImageIcon(new ImageIcon(duongDan).getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH));
            lblHinhAnh.setIcon(hinhAnh);
        }
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        if (!txtSoLuong.getText().isEmpty() && !txtDonGia.getText().isEmpty() && Integer.parseInt(txtSoLuong.getText())>0) {
            int thanhTien = Integer.parseInt(txtSoLuong.getText()) * Integer.parseInt(txtDonGia.getText().replace(",", ""));
            DecimalFormat df = new DecimalFormat("###,###");
            txtThanhTien.setText(df.format(thanhTien));
        } else if(Integer.parseInt(txtSoLuong.getText())<0){
            JOptionPane.showMessageDialog(this, "Số Lượng phải lớn hơn 0");
        }else{
            JOptionPane.showMessageDialog(this, "Không đủ dữ kiện tính toán");
        }
    }//GEN-LAST:event_btnTinhTienActionPerformed

    public void KetNoiCSDL() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433; databaseName = QUANLY_DIENTHOAI";
        String user = "sa";
        String pass = "123456";
        ketNoi = DriverManager.getConnection(url, user, pass);
    }

    public void DatTenCotPhongHoc() {
        model.addColumn("Tên Điện Thoại");
        model.addColumn("Hãng Sản Xuất");
        model.addColumn("Số Lượng");
        model.addColumn("Đơn Giá");
        model.addColumn("Thành Tiền");
        model.addColumn("Hình Ảnh");

        tblBang.setModel(model);
    }

    public void DoDuLieuLenBang() throws ClassNotFoundException, SQLException {
        model.setRowCount(0);
        KetNoiCSDL();
        String sql = "SELECT * FROM DIENTHOAI";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        DecimalFormat df = new DecimalFormat("###,###");
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            String tenDienThoai = ketQua.getString(1);
            String hangSanXuat = ketQua.getString(2);
            int soLuong = ketQua.getInt(3);

            int donGia = ketQua.getInt(4);
            int tongTien = soLuong * donGia;
            String donGiaFormatted = df.format(donGia);
            String tongTienFormatted = df.format(tongTien);
            String HinhAnh = ketQua.getString(5);

            model.addRow(new Object[]{tenDienThoai, hangSanXuat, soLuong, donGiaFormatted, tongTienFormatted, HinhAnh});
        }
        ketNoi.close();
    }

    public void DanhSachGiay() throws ClassNotFoundException, SQLException {
        int viTri = tblBang.getSelectedRow();
        DecimalFormat df = new DecimalFormat("###,###");
        txtTenDienThoai.setText(tblBang.getValueAt(viTri, 0).toString());
        cboHangSanXuat.setSelectedItem(tblBang.getValueAt(viTri, 1).toString());
        txtSoLuong.setText(tblBang.getValueAt(viTri, 2).toString());
        txtDonGia.setText(tblBang.getValueAt(viTri, 3).toString());
        txtThanhTien.setText(tblBang.getValueAt(viTri, 4).toString());

        KetNoiCSDL();
        String sql = "SELECT HinhAnh FROM DIENTHOAI WHERE TENDIENTHOAI = ? ";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        cauLenh.setString(1, tblBang.getValueAt(viTri, 0).toString());

        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            duongDan = ketQua.getString(1);
            ImageIcon hinhanh = new ImageIcon(new ImageIcon(duongDan).getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH));
            lblHinhAnh.setIcon(hinhanh);
        }
        ketNoi.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FinalTest().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FinalTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHangSanXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenDienThoai;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
